# Generated by Django 4.2.2 on 2023-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('recordid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sleep', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('yoga', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('gym', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('walking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('reading', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('skills_development', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=10)),
                ('expenses', models.IntegerField()),
                ('todays_dairy', models.TextField(max_length=500)),
            ],
        ),
    ]
