# Generated by Django 4.2.2 on 2023-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_delete_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gym_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='reading_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='skills_development_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='sleep_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='walking_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='yoga_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='gym',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='reading',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='skills_development',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='sleep',
            field=models.CharField(choices=[('1-3', '1 to 3 hours scores 15'), ('3-5', '3 to 5 hours scores 10'), ('5-7', '5 to 7 hours scores 5'), ('7+', 'Above 7 hours scores 0')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='walking',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='yoga',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1')], max_length=4),
        ),
    ]
