# Generated by Django 4.2.2 on 2023-06-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_score_remove_record_gym_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
