# Generated by Django 4.2.2 on 2023-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_water_intake_score_water_intake_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gym',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1'), ('0', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='reading',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1'), ('0', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='skills_development',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1'), ('0', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='walking',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1'), ('0', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='yoga',
            field=models.CharField(choices=[('60', '60 mins scores 10'), ('45', '45 mins scores 5'), ('30', '30 mins scores 2'), ('15', '15 mins scores 1'), ('0', 'none')], max_length=4),
        ),
    ]
